services:
  gcp_api:
    build:
      context: ./backend/src/
      dockerfile: GoogleCloudStorage.Dockerfile
    image: europe-west1-docker.pkg.dev/epaper-picture-frames/epaper-picture-frames-apis/google-cloud-storage
    env_file: .ENV
    container_name: gcp_api
    ports:
      - 3000:8080